apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: api-python:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: sqlite:///alunos.db
        ports:
        - containerPort: 3000