services:
  api-js:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - app_volume:/app
    environment:
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: ${DB_HOST:-postgres}
      DB_DIALECT: ${DB_DIALECT:-postgres}
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mydb}
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:9.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  app_volume: