name: API-JS CI

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SONAR_ORGANIZATION:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_PROJECT_KEY:
        required: true

jobs:
  build:
    uses: ./.github/workflows/api-js-build.yml
  code-quality-and-security:
    needs: build
    uses: ./.github/workflows/api-js-code-quality-and-security.yml
    secrets:
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  tests:
    needs: code-quality-and-security
    uses: ./.github/workflows/api-js-tests.yml
  docker:
    needs: tests
    uses: ./.github/workflows/api-js-docker.yml
 