name: APIJS PIPELINE

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'APIs para exercícios/api-js/**'
jobs: 
  ci:
    uses: ./.github/workflows/api-js-ci.yml
    secrets:
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  cd: 
    uses: ./.github/workflows/api-js-cd.yml
    needs: ci
    secrets:
      HML_DEPLOY_HOOK: ${{ secrets.HML_DEPLOY_HOOK }}